### ISSUE TITLE
Colony names all showing as 'Earth'

### ISSUE THREAD

**Issue by CountCristo** [Aurora-Modders/AuroraLoader#66]
**Describe the bug**
All colonies show as 'Earth' in the F2 window.

**To Reproduce**
1. make a second colony
2. Open the F2 window
3. Look at colony names

**Expected behavior**
Colonies show up with the correct names

**Screenshots**
All Colonies are called 'Earth

**Environment (please complete the following information):**
 - OS: Windows 10
 - AuroraLoader version: 0.25.3
 - Aurora version: 1.12.0
- Installed/selected mods and versions: ArouraMod, Standard Components Renaming (Values), Standard Components Renaming  (size in tons)

**Additional context**
N/A

Image of the bug: https://cdn.discordapp.com/attachments/417352964974313472/789320509346152448/unknown.png

**Comment by Revoric** [comment]
That's a known bug with Aurora mod, select "By Function" or "System Body" and it clears the problem right up.

![image](https://user-images.githubusercontent.com/38903281/102713021-ba183200-428a-11eb-9b80-f85685ecb1d3.png)

**Comment by CountCristo** [comment]
I'm back 2 years later realizing I never thanked you for the help - so here I am, thank you :)

**Comment by Revoric** [comment]
Haha better late then never! :) greetings from the past and future
